version: "3"
services:
  ipinfo:
    container_name: ipinfo
    image: ghcr.io/lstellway/ipinfo:latest
    environment:
        APP_PORT: 8080
    ports:
        - 8080:8080
    restart: unless-stopped
