version: "3.8"
services:
  docker-gitlab-runner:
    container_name: docker-gitlab-runner
    image: ghcr.io/lstellway/docker-gitlab-runner:latest
    # As of writing, the `privileged` option is required for Docker in Docker to function.
    # Sysbox is an alternative runtime that removes the need for running as a privileged container:
    # @see https://github.com/nestybox/sysbox#performance
    privileged: true
    volumes:
      - gitlab-runner-data:/home/rootless/.gitlab-runner

volumes:
  gitlab-runner-data:
    name: gitlab-runner-data
