name: Build Docker Image

on:
    push:
        # Tag matching with regex
        # @see https://github.com/actions/runner/issues/1699#issuecomment-1046796067
        tags:
            # Stable
            - "[0-9]+.[0-9]+.[0-9]+"
            # Alpha
            - "[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+"
            # Beta
            - "[0-9]+.[0-9]+.[0-9]+-beta[0-9]+"

jobs:
    build:
        strategy:
            matrix:
                image_name:
                    - backup-mysql-s3
                    - ddns-cloudflare
                    - digitalocean-floating-ip
                    - docker-gitlab-runner
                    - ipinfo
                    - s3fs-fuse
                    - sync-s3
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Extract variables
              run: |
                  # Relative path to the Dockerfile
                  DOCKERFILE="./${{ matrix.image_name }}/Dockerfile"
                  echo "DOCKERFILE=${DOCKERFILE}" >> $GITHUB_ENV

                  # Parse metadata from JSON
                  [ -f "./${{ matrix.image_name }}/image.json" ] && IMAGE_META=$(cat "./${{ matrix.image_name }}/image.json" | tr '\n' ' ') || IMAGE_META="{}"
                  echo "IMAGE_META=${IMAGE_META}" >> $GITHUB_ENV

            - name: Parse image meta
              run: |
                  # Determine build platforms
                  DOCKER_PLATFORMS="${{ fromJson(env.IMAGE_META).platforms || '' }}"
                  [ -n "${DOCKER_PLATFORMS}" ] || DOCKER_PLATFORMS="linux/amd64,linux/arm64"
                  echo "DOCKER_PLATFORMS=${DOCKER_PLATFORMS}" >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

            - name: Available platforms
              run: echo ${{ steps.buildx.outputs.platforms }}

            - name: Login to GitHub Container Registry
              run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
                  cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
                  context: ${{ matrix.image_name }}
                  file: ${{ env.DOCKERFILE }}
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.ref_name }}
                      ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
                  platforms: ${{ env.DOCKER_PLATFORMS }}
