name: Build Docker Image

on:
  push:
    tags: ["*"]
  workflow_dispatch:
    inputs:
      build_tag:
        required: true
        description: The full container image tag (eg. `docker-gitlab-runner:0.1.0-alpha2`)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract variables
        run: |
          # Get the target tag from either:
          # 1. The workflow input variable
          # 2. The build tag
          [ -n "${{ github.event.inputs.build_tag }}" ] && SOURCE_TAG="${{ github.event.inputs.build_tag }}" || SOURCE_TAG="${GITHUB_REF##*/}"
          echo "SOURCE_TAG=${SOURCE_TAG}" >> $GITHUB_ENV

          # Target image name
          IMAGE_NAME=$(echo $SOURCE_TAG | cut -d':' -f 1)
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

          # Target version (tag)
          IMAGE_VERSION=$(echo $SOURCE_TAG | cut -d':' -f 2)
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV

          # Relative path to the Dockerfile
          DOCKERFILE="./${IMAGE_NAME}/Dockerfile"
          echo "DOCKERFILE=${DOCKERFILE}" >> $GITHUB_ENV

          # Ensure the Dockerfile exists
          ([ -f "${DOCKERFILE}" ] && [ -n "${IMAGE_VERSION}" ]) && PROCESS_IMAGE="true" || PROCESS_IMAGE="false"
          echo "PROCESS_IMAGE=${PROCESS_IMAGE}" >> $GITHUB_ENV

          # Parse metadata from JSON
          [ -f "./${IMAGE_NAME}/image.json" ] && IMAGE_META=$(cat "./${IMAGE_NAME}/image.json" | tr '\n' ' ') || IMAGE_META="{}"
          echo "IMAGE_META=${IMAGE_META}" >> $GITHUB_ENV

      - name: Parse image meta
        run: |
          # Determine build platforms
          DOCKER_PLATFORMS="${{ fromJson(env.IMAGE_META).platforms || '' }}"
          [ -n "${DOCKER_PLATFORMS}" ] || DOCKER_PLATFORMS="linux/amd64,linux/arm64"
          echo "DOCKER_PLATFORMS=${DOCKER_PLATFORMS}" >> $GITHUB_ENV

      - name: Dump variables
        run: echo $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: ${{ env.PROCESS_IMAGE == 'true' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: ${{ env.PROCESS_IMAGE == 'true' }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ env.PROCESS_IMAGE == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # password: ${{ github.token }}
          password: ${{ secrets.GHCR_TOKEN }}
          logout: true

      # - name: Login to GitHub Container Registry
      #   run: echo "${{ github.token }}" | docker login ghcr.io -u $ --password-stdin
      #   if: ${{ env.DOCKERFILE_EXISTS == 'true' && env.PROCESS_IMAGE == 'true' }}

      - name: Build and push
        uses: docker/build-push-action@v4
        if: ${{ env.PROCESS_IMAGE == 'true' }}
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          # build-args: |
          #   "ROOT_DIR=${{ secrets.ROOT_DIR }}"
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          platforms: ${{ env.DOCKER_PLATFORMS }}

